package com.teamalfa.kidslearningapp;

public class ImageArrayHelper {
    public int[] itemBanglaSorbornoAlphabeticImage = new int[]{R.drawable.shoro_1, R.drawable.shoro_2, R.drawable.shoro_3, R.drawable.shoro_4, R.drawable.shoro_5, R.drawable.shoro_6, R.drawable.shoro_7, R.drawable.shoro_8, R.drawable.shoro_9, R.drawable.shoro_10, R.drawable.shoro_11};
    public int[] itemBanglaBenjonbornoAlphabeticImage = new int[]{R.drawable.bhenj_1, R.drawable.bhenj_2, R.drawable.bhenj_3, R.drawable.bhenj_4, R.drawable.bhenj_5, R.drawable.bhenj_6, R.drawable.bhenj_7, R.drawable.bhenj_8, R.drawable.bhenj_9, R.drawable.bhenj_10, R.drawable.bhenj_11, R.drawable.bhenj_12, R.drawable.bhenj_13, R.drawable.bhenj_14, R.drawable.bhenj_15, R.drawable.bhenj_16, R.drawable.bhenj_17, R.drawable.bhenj_18, R.drawable.bhenj_19, R.drawable.bhenj_20, R.drawable.bhenj_21, R.drawable.bhenj_22, R.drawable.bhenj_23, R.drawable.bhenj_24, R.drawable.bhenj_25, R.drawable.bhenj_26, R.drawable.bhenj_27, R.drawable.bhenj_28, R.drawable.bhenj_29, R.drawable.bhenj_30, R.drawable.bhenj_31, R.drawable.bhenj_32, R.drawable.bhenj_33, R.drawable.bhenj_34, R.drawable.bhenj_35, R.drawable.bhenj_36, R.drawable.bhenj_37, R.drawable.bhenj_38, R.drawable.bhenj_39, R.drawable.bhenj_40};
    public int[] itemEnglishAlphabetImage = new int[]{R.drawable.alphabet_en_1, R.drawable.alphabet_en_2, R.drawable.alphabet_en_3, R.drawable.alphabet_en_4, R.drawable.alphabet_en_5, R.drawable.alphabet_en_6, R.drawable.alphabet_en_7, R.drawable.alphabet_en_8, R.drawable.alphabet_en_9, R.drawable.alphabet_en_10, R.drawable.alphabet_en_11, R.drawable.alphabet_en_12, R.drawable.alphabet_en_13, R.drawable.alphabet_en_14, R.drawable.alphabet_en_15, R.drawable.alphabet_en_16, R.drawable.alphabet_en_17, R.drawable.alphabet_en_18, R.drawable.alphabet_en_19, R.drawable.alphabet_en_20, R.drawable.alphabet_en_21, R.drawable.alphabet_en_22, R.drawable.alphabet_en_23, R.drawable.alphabet_en_24, R.drawable.alphabet_en_25, R.drawable.alphabet_en_26};
    public int[] itemBanglaSubjectImage = new int[]{R.drawable.sorborno, R.drawable.benjonborno, R.drawable.bangla_item_3,R.drawable.bangla_item_4,R.drawable.bangla_item_5,R.drawable.bangla_item_6,R.drawable.bangla_item_7,R.drawable.bangla_item_5,R.drawable.bangla_item_6,R.drawable.bangla_item_7};
    public int[] itemEnglishSubjectImage = new int[]{R.drawable.english_item_1,R.drawable.english_item_2,R.drawable.english_item_3,R.drawable.english_item_4,R.drawable.english_item_4,R.drawable.englis,R.drawable.english_item_4,R.drawable.english_item_4};
    public int[] itemMathSubjectImage = new int[]{R.drawable.math_item_2,R.drawable.math_item_1,R.drawable.math_item_2,R.drawable.math_item_1,R.drawable.math_item_2,R.drawable.math_item_1,R.drawable.math_item_2,R.drawable.math_item_1,R.drawable.math_item_2,R.drawable.math_item_1,R.drawable.math_item_2,R.drawable.math_item_1,R.drawable.math_item_2,R.drawable.math_item_1};
    public int[] itemArabicSubjectImage = new int[]{R.drawable.arabic_item_1,R.drawable.arabic_item_2,R.drawable.arabic_item_1};
    public int[] itemHandWritingImage = new int[] {R.drawable.sorborno,R.drawable.benjonborno,R.drawable.english_item_1,R.drawable.english_item_2,R.drawable.arabic_item_1,R.drawable.math_item_2,R.drawable.math_item_1};
}
